import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "./components/Nav";
import { Toaster } from "sonner";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <header>
            <Nav />
          </header>
          <main className="flex-1 flex flex-col">{children}</main>
          <footer className="bg-base-200 mt-12 py-8 text-center text-sm opacity-40">
            &copy; {new Date().getFullYear()} Chip Review. All rights reserved.
          </footer>
          <Toaster position="top-right" richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
