drop extension if exists "pg_net";


  create table "public"."brands" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "description" text,
    "logo_url" text,
    "slug" text not null
      );


alter table "public"."brands" enable row level security;


  create table "public"."chips" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "description" text,
    "brand_id_fk" bigint not null,
    "photo_url" text,
    "user_id_fk" uuid not null default auth.uid(),
    "slug" text not null
      );


alter table "public"."chips" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "username" text not null,
    "email" text not null,
    "avatar_url" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."profiles" enable row level security;


  create table "public"."reviews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "review" text not null,
    "photo_url" text,
    "rating" smallint not null,
    "user_id_fk" uuid not null,
    "chips_id_fk" bigint not null
      );


alter table "public"."reviews" enable row level security;

CREATE UNIQUE INDEX brands_name_key ON public.brands USING btree (name);

CREATE UNIQUE INDEX brands_pkey ON public.brands USING btree (id);

CREATE UNIQUE INDEX brands_slug_key ON public.brands USING btree (slug);

CREATE UNIQUE INDEX chips_pkey ON public.chips USING btree (id);

CREATE UNIQUE INDEX chips_slug_key ON public.chips USING btree (slug);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

alter table "public"."brands" add constraint "brands_pkey" PRIMARY KEY using index "brands_pkey";

alter table "public"."chips" add constraint "chips_pkey" PRIMARY KEY using index "chips_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."brands" add constraint "brands_name_key" UNIQUE using index "brands_name_key";

alter table "public"."brands" add constraint "brands_slug_key" UNIQUE using index "brands_slug_key";

alter table "public"."chips" add constraint "chips_brand_id_fk_fkey" FOREIGN KEY (brand_id_fk) REFERENCES public.brands(id) not valid;

alter table "public"."chips" validate constraint "chips_brand_id_fk_fkey";

alter table "public"."chips" add constraint "chips_slug_key" UNIQUE using index "chips_slug_key";

alter table "public"."chips" add constraint "chips_user_id_fk_fkey" FOREIGN KEY (user_id_fk) REFERENCES public.profiles(id) not valid;

alter table "public"."chips" validate constraint "chips_user_id_fk_fkey";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."profiles" add constraint "username_length" CHECK ((char_length(username) >= 3)) not valid;

alter table "public"."profiles" validate constraint "username_length";

alter table "public"."reviews" add constraint "reviews_chips_id_fk_fkey" FOREIGN KEY (chips_id_fk) REFERENCES public.chips(id) not valid;

alter table "public"."reviews" validate constraint "reviews_chips_id_fk_fkey";

alter table "public"."reviews" add constraint "reviews_user_id_fk_fkey" FOREIGN KEY (user_id_fk) REFERENCES public.profiles(id) not valid;

alter table "public"."reviews" validate constraint "reviews_user_id_fk_fkey";

set check_function_bodies = off;

create or replace view "public"."chips_with_stats" as  SELECT c.id,
    c.created_at,
    c.updated_at,
    c.name,
    c.description,
    c.brand_id_fk,
    c.photo_url,
    c.user_id_fk,
    c.slug,
    count(r.id) AS review_count,
    round(avg(r.rating), 1) AS average_rating
   FROM (public.chips c
     LEFT JOIN public.reviews r ON ((r.chips_id_fk = c.id)))
  GROUP BY c.id;


CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, email, username, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

grant delete on table "public"."brands" to "anon";

grant insert on table "public"."brands" to "anon";

grant references on table "public"."brands" to "anon";

grant select on table "public"."brands" to "anon";

grant trigger on table "public"."brands" to "anon";

grant truncate on table "public"."brands" to "anon";

grant update on table "public"."brands" to "anon";

grant delete on table "public"."brands" to "authenticated";

grant insert on table "public"."brands" to "authenticated";

grant references on table "public"."brands" to "authenticated";

grant select on table "public"."brands" to "authenticated";

grant trigger on table "public"."brands" to "authenticated";

grant truncate on table "public"."brands" to "authenticated";

grant update on table "public"."brands" to "authenticated";

grant delete on table "public"."brands" to "service_role";

grant insert on table "public"."brands" to "service_role";

grant references on table "public"."brands" to "service_role";

grant select on table "public"."brands" to "service_role";

grant trigger on table "public"."brands" to "service_role";

grant truncate on table "public"."brands" to "service_role";

grant update on table "public"."brands" to "service_role";

grant delete on table "public"."chips" to "anon";

grant insert on table "public"."chips" to "anon";

grant references on table "public"."chips" to "anon";

grant select on table "public"."chips" to "anon";

grant trigger on table "public"."chips" to "anon";

grant truncate on table "public"."chips" to "anon";

grant update on table "public"."chips" to "anon";

grant delete on table "public"."chips" to "authenticated";

grant insert on table "public"."chips" to "authenticated";

grant references on table "public"."chips" to "authenticated";

grant select on table "public"."chips" to "authenticated";

grant trigger on table "public"."chips" to "authenticated";

grant truncate on table "public"."chips" to "authenticated";

grant update on table "public"."chips" to "authenticated";

grant delete on table "public"."chips" to "service_role";

grant insert on table "public"."chips" to "service_role";

grant references on table "public"."chips" to "service_role";

grant select on table "public"."chips" to "service_role";

grant trigger on table "public"."chips" to "service_role";

grant truncate on table "public"."chips" to "service_role";

grant update on table "public"."chips" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."brands"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."brands"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."chips"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."chips"
  as permissive
  for select
  to public
using (true);



  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile."
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can update own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable delete for users based on user_id"
  on "public"."reviews"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = user_id_fk));



  create policy "Enable insert for authenticated users only"
  on "public"."reviews"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."reviews"
  as permissive
  for select
  to public
using (true);



  create policy "can update own review"
  on "public"."reviews"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id_fk))
with check ((auth.uid() = user_id_fk));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Anyone can view 15kep2a_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'brand-logos'::text));



  create policy "Anyone can view and3c2_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'chip-photos'::text));



  create policy "Authenticated users can upload 15kep2a_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'brand-logos'::text));



  create policy "Authenticated users can upload and3c2_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'chip-photos'::text));



  create policy "anyone can view 1tsy3yu_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'review-photos'::text));



  create policy "only signed in users can add  1tsy3yu_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'review-photos'::text));



  create policy "ownership 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "ownership 1oj01fe_1"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "ownership 1oj01fe_2"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "ownership 1oj01fe_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



